### PR TITLE
Enable `java` syntax highlighting

### PR DESCRIPTION
**Pull request by 72636c**

### CODE REVIEW

**Review by AaronMoat — APPROVED** [review]
Excellent

**Comment by 72636c** [comment]
I don't know why CI is broken but I assume it's a sign from a higher power that this is not meant to be

**Review by tadhglewis — APPROVED** [review]
PHPified

**Comment by 72636c** [comment]
Closed by #732

**Comment by 72636c** [comment]
Oops, I'm wrong

**Comment by 72636c** [comment]
I have no energy to try to fix PHP

**Pull request merged**
